// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("paralleltests")>]
[<assembly: AssemblyProductAttribute("canopy")>]
[<assembly: AssemblyVersionAttribute("2.1.3")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-03-07T00:00:00.0000000-06:00")>]
[<assembly: AssemblyFileVersionAttribute("2.1.3")>]
[<assembly: AssemblyInformationalVersionAttribute("2.1.3")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","d4bd2b919c8ab9142ed6bca402415c92d76c5eab")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "paralleltests"
    let [<Literal>] AssemblyProduct = "canopy"
    let [<Literal>] AssemblyVersion = "2.1.3"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-03-07T00:00:00.0000000-06:00"
    let [<Literal>] AssemblyFileVersion = "2.1.3"
    let [<Literal>] AssemblyInformationalVersion = "2.1.3"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "d4bd2b919c8ab9142ed6bca402415c92d76c5eab"
