// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("canopy")>]
[<assembly: AssemblyProductAttribute("canopy")>]
[<assembly: AssemblyDescriptionAttribute("F# web testing framework")>]
[<assembly: AssemblyVersionAttribute("1.4.5")>]
[<assembly: AssemblyFileVersionAttribute("1.4.5")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "canopy"
    let [<Literal>] AssemblyProduct = "canopy"
    let [<Literal>] AssemblyDescription = "F# web testing framework"
    let [<Literal>] AssemblyVersion = "1.4.5"
    let [<Literal>] AssemblyFileVersion = "1.4.5"
