// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("canopy")>]
[<assembly: AssemblyProductAttribute("canopy")>]
[<assembly: AssemblyDescriptionAttribute("F# web testing framework")>]
[<assembly: AssemblyVersionAttribute("1.5.2")>]
[<assembly: AssemblyFileVersionAttribute("1.5.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "canopy"
    let [<Literal>] AssemblyProduct = "canopy"
    let [<Literal>] AssemblyDescription = "F# web testing framework"
    let [<Literal>] AssemblyVersion = "1.5.2"
    let [<Literal>] AssemblyFileVersion = "1.5.2"
