// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("canopy.integration")>]
[<assembly: AssemblyProductAttribute("canopy.integration")>]
[<assembly: AssemblyDescriptionAttribute("F# web testing framework")>]
[<assembly: AssemblyVersionAttribute("1.6.1")>]
[<assembly: AssemblyFileVersionAttribute("1.6.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "canopy.integration"
    let [<Literal>] AssemblyProduct = "canopy.integration"
    let [<Literal>] AssemblyDescription = "F# web testing framework"
    let [<Literal>] AssemblyVersion = "1.6.1"
    let [<Literal>] AssemblyFileVersion = "1.6.1"
